version: '3'
services:
  kubelet:
      image: dkhub.funceme.br:444/unisp/kubernetes/kubelet:1.9.8
      restart: always
      container_name: kubelet
      hostname: <hostname_minio>
      network_mode: "host"
      ports: 
        - 10250:10250
        - 10255:10255 
      privileged: true
      environment:
        - ETCD_SERVER=<dns_name_etcd_server>
        - ETCD_PREFIX=<prefix_network_etcd>
        - CLUSTER_NAME=<cluster_name>
      volumes:
        - /mnt/nas/kubernetes/certs:/opt/kubernetes/certs/
        - /sys/fs/cgroup:/sys/fs/cgroup
  kube-proxy:
      image: dkhub.funceme.br:444/unisp/kubernetes/kube-proxy:1.9.8
      restart: always
      container_name: kube-proxy
      hostname: kube-proxy
      network_mode: "host"
      privileged: true
      environment:
        - APISERVER_IP=<dns_name_api_kubernetes>
        - HOSTNAME_OVERRIDE=<hostname_minio>
      volumes:
        - /mnt/nas/kubernetes/certs:/opt/kubernetes/certs/
        - /sys/fs/cgroup:/sys/fs/cgroup