version: '3'
services:
  etcd:
    image: dkhub.funceme.br:444/unisp/kubernetes/etcdserver:2.3.8
    restart: always
    container_name: etcd
    hostname: etcd
    ports: 
      - 2379:2379
      - 2380:2380
    privileged: true
    environment:
      - ETCD_PREFIX=/funceme.local/network
    volumes:
      - /opt/etcd:/opt/etcd/data
  kube-apiserver:
    image: jonascavalcantineto/kube-apiserver:1.9.8
    restart: always
    container_name: kube-apiserver
    hostname: kube-apiserver
    ports: 
      - 6443:6443
    privileged: true
    environment:
      - ETCD_SERVER=<dns_name_etcd_server>
      - APISERVER_IP=<dns_name_api_kubernetes>
      - CLUSTER_NAME=<cluster_name>
    volumes:
      - /mnt/nas/kubernetes/certs:/opt/kubernetes/certs/
  kube-controller-manager:
    image: dkhub.funceme.br:444/unisp/kubernetes/kube-controller-manager:1.9.8
    restart: always
    container_name: kube-controller-manager
    hostname: kube-controller-manager
    ports: 
      - 10252:10252
    privileged: true
    environment:
      - CLUSTER_NAME=<cluster_name>
    volumes:
      - /mnt/nas/kubernetes/certs:/opt/kubernetes/certs/
  kube-scheduler:
    image: dkhub.funceme.br:444/unisp/kubernetes/kube-scheduler:1.9.8
    restart: always
    container_name: kube-scheduler
    hostname: kube-scheduler
    ports: 
      - 10251:10251
    privileged: true
    volumes:
      - /mnt/nas/kubernetes/certs:/opt/kubernetes/certs/